chore(web-monetization-demo): remove mini accounts plugin
This currently causes build:ts to fail with:

src/server/StreamServer.ts(21,46): error TS2741: Property 'isConnected' is missing in type 'import("/home/brandon/web-monetization-projects/node_modules/ilp-plugin/dist/index").Plugin' but required in type 'import("/home/brandon/ilp-protocol-stream/dist/src/util/plugin-interface").Plugin'.